name: slideutils
channels:
  - conda-forge
dependencies:
  - python==3.9.7
  - numpy==1.21.4
  - pandas==1.3.5
  - py-opencv==4.5.3
  - scikit-image==0.19.1
  - pip==21.3.1
  - pip:
    - h5py==3.6.0

